// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoYUAkLtI5vsYmdVVJKjOCYY91tiUdn6c',
    appId: '1:364338584216:web:25e66642e23d2b6d73ceed',
    messagingSenderId: '364338584216',
    projectId: 'kino-96bb3',
    authDomain: 'kino-96bb3.firebaseapp.com',
    storageBucket: 'kino-96bb3.firebasestorage.app',
    measurementId: 'G-NFGC2YB1M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNSsZwrHfS7tf0rZK66RqQnY7taTJC-Wo',
    appId: '1:364338584216:android:f1cfe38eae8ebec573ceed',
    messagingSenderId: '364338584216',
    projectId: 'kino-96bb3',
    storageBucket: 'kino-96bb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3IieXCKjRpNbTmIKxXaipGeQRk9Pok38',
    appId: '1:364338584216:ios:fe43114f24f2e75973ceed',
    messagingSenderId: '364338584216',
    projectId: 'kino-96bb3',
    storageBucket: 'kino-96bb3.firebasestorage.app',
    iosBundleId: 'com.example.kinoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3IieXCKjRpNbTmIKxXaipGeQRk9Pok38',
    appId: '1:364338584216:ios:fe43114f24f2e75973ceed',
    messagingSenderId: '364338584216',
    projectId: 'kino-96bb3',
    storageBucket: 'kino-96bb3.firebasestorage.app',
    iosBundleId: 'com.example.kinoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoYUAkLtI5vsYmdVVJKjOCYY91tiUdn6c',
    appId: '1:364338584216:web:40e4547b3a3daafc73ceed',
    messagingSenderId: '364338584216',
    projectId: 'kino-96bb3',
    authDomain: 'kino-96bb3.firebaseapp.com',
    storageBucket: 'kino-96bb3.firebasestorage.app',
    measurementId: 'G-MRPKQ9MRW7',
  );
}
